name: .NET Vulnerability Scan

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Adjust to your SDK version

      - name: Restore all solutions
        run: |
          find . -name "*.sln" -print0 | while IFS= read -r -d '' sln; do
            echo "🔧 Restoring: $sln"
            dotnet restore "$sln"
          done

      - name: Check for vulnerabilities
        run: |
          echo "🔍 Checking for vulnerable packages..."

          VULN_FOUND=0

          find . -name "*.sln" -print0 | while IFS= read -r -d '' sln; do
            echo "🔎 Scanning solution: $sln"
            OUTPUT=$(dotnet list "$sln" package --vulnerable)

            echo "$OUTPUT"
            echo ""

            if echo "$OUTPUT" | grep -q "has the following vulnerable packages"; then
              echo "❌ Vulnerabilities found in: $sln"
              VULN_FOUND=1
            else
              echo "✅ No vulnerabilities found in: $sln"
            fi

            echo "--------------------------------------"
          done

          if [ $VULN_FOUND -eq 1 ]; then
            echo "❌ Vulnerabilities detected in one or more solutions."
            exit 1
          else
            echo "✅ No vulnerabilities found across all solutions."
          fi
