name: Check for Vulnerable NuGet Packages

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  scan:
    name: Scan NuGet Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # adjust as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Check for vulnerabilities
        run: dotnet list package --vulnerable
