name: Check for Vulnerable NuGet Packages

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  scan:
    name: Scan NuGet Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # adjust as needed

      - name: Find all .sln files
        id: find_sln
        run: |
          sln_files=$(find . -name '*.sln')
          echo "Found solution files: $sln_files"
          echo "::set-output name=sln_files::$sln_files"

      - name: Restore dependencies and check for vulnerabilities for each solution
        run: |
          for sln in ${{ steps.find_sln.outputs.sln_files }}; do
            echo "Restoring dependencies for $sln"
            dotnet restore "$sln"
            echo "Checking for vulnerabilities in $sln"
            dotnet list "$sln" package --vulnerable
          done
